.TH "core Directory Reference" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcommon\fP"
.br
.ti -1c
.RI "directory \fBproperties\fP"
.br
.ti -1c
.RI "directory \fBtransitions\fP"
.br
.in -1c
