.TH "core/properties Directory Reference" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/properties Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdeposition_auto_conversion\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdeposition_factor\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfall_speed\&.hpp\fP"
.br
.ti -1c
.RI "file \fBice_deposition\&.hpp\fP"
.br
.ti -1c
.RI "file \fBice_mass\&.hpp\fP"
.br
.ti -1c
.RI "file \fBice_number\&.hpp\fP"
.br
.ti -1c
.RI "file \fBice_sticking\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsnow_lambda\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsnow_number\&.hpp\fP"
.br
.ti -1c
.RI "file \fBthermo\&.hpp\fP"
.br
.ti -1c
.RI "file \fBvel_scale_factor\&.hpp\fP"
.br
.in -1c
