.TH "core/transitions/cloud_to_snow.hpp" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/transitions/cloud_to_snow.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./common/constants\&.hpp'\fP
.br
\fR#include '\&.\&./common/types\&.hpp'\fP
.br
\fR#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtransition\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBtransition::cloud_to_snow\fP (\fBreal_t\fP \fBt\fP, \fBreal_t\fP \fBqc\fP, \fBreal_t\fP \fBqs\fP, \fBreal_t\fP \fBns\fP, \fBreal_t\fP \fBlambda\fP)"
.br
.RI "Calculates the riming snow rate from cloud water\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::ecs\fP"
.br
.RI "Collection efficiency for snow collecting cloud water\&. "
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::b_rim_\fP = \-(\fBgraupel_ct::v1s\fP + \fBstatic_cast\fP<\fBreal_t\fP>(3\&.0))"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::c_rim\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
