.TH "core/transitions/cloud_to_rain.hpp" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/transitions/cloud_to_rain.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./common/constants\&.hpp'\fP
.br
\fR#include '\&.\&./common/types\&.hpp'\fP
.br
\fR#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtransition\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBtransition::cloud_to_rain\fP (\fBreal_t\fP \fBt\fP, \fBreal_t\fP \fBqc\fP, \fBreal_t\fP \fBqr\fP, \fBreal_t\fP \fBnc\fP)"
.br
.RI "Calculates the conversion rate from cloud water to rain water\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::qmin_ac\fP = 1\&.00e\-06"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::tau_max\fP = 0\&.90e+00"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::tau_min\fP = 1\&.00e\-30"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::a_phi\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::b_phi\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::c_phi\fP = 5\&.00e\-05"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::ac_kernel\fP = 5\&.25\fBe\fP+00"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::x3\fP = 2\&.00e+00"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::x2\fP = 2\&.60e\-10"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::x1\fP = 9\&.44\fBe\fP+09"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
