.TH "test/common.cc" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/common.cc
.SH SYNOPSIS
.br
.PP
\fR#include <gtest/gtest\&.h>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <type_traits>\fP
.br
\fR#include 'MuphysTest\&.cc'\fP
.br
\fR#include 'core/common/graupel\&.hpp'\fP
.br
\fR#include 'core/common/utils\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBCommonTest\fP, \fBCommonTestSuite_CheckPrecision\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_DepAutoConversion_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_DepAutoConversion\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_IceDepositionNucleation_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_IceDepositionNucleation\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_DepFactor\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_FallSpeed\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_IceSticking\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_IceNumber\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_IceMass\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_SnowLambda_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_SnowLambda\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_SnowNumber_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_SnowNumber\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_VelScaleFactor_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_VelScaleFactor_ice\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBPropertyTestSuite_VelScaleFactor_snow\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBThermoTestSuite_InternalEnergy\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBThermoTestSuite_T_InternalEnergy\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBThermoTestSuite_SatPresWater\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBThermoTestSuite_SatPresIce\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBThermoTestSuite_QSatRho\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBThermoTestSuite_QSatIceRho\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToGraupel_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToGraupel\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToRain_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToRain\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToSnow_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToSnow\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudXIce_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudXIce_i\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudXIce_c\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_GraupelToRain_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_GraupelToRain\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_IceToGraupel_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_IceToGraupel_r\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_IceToGraupel_g\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_IceToSnow_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_IceToSnow\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToGraupel_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToGraupel_1\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToGraupel_2\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToGraupel_3\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToVapor_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToVapor\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_SnowToGraupel_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_SnowToGraupel\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_SnowToRain_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_SnowToRain\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXGraupel_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXGraupel\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXSnow_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXSnow\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXIce_default\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXIce\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBUtilsTestSuite\fP, \fBCalcDz\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (\fBCommonTest\fP, \fBCommonTestSuite_CheckPrecision\fP)"

.PP
Definition at line \fB20\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST (\fBUtilsTestSuite\fP, \fBCalcDz\fP)"

.PP
Definition at line \fB660\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_DepAutoConversion\fP)"

.PP
Definition at line \fB37\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_DepAutoConversion_default\fP)"

.PP
Definition at line \fB28\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_DepFactor\fP)"

.PP
Definition at line \fB73\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_FallSpeed\fP)"

.PP
Definition at line \fB82\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_IceDepositionNucleation\fP)"

.PP
Definition at line \fB60\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_IceDepositionNucleation_default\fP)"

.PP
Definition at line \fB48\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_IceMass\fP)"

.PP
Definition at line \fB106\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_IceNumber\fP)"

.PP
Definition at line \fB96\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_IceSticking\fP)"

.PP
Definition at line \fB89\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_SnowLambda\fP)"

.PP
Definition at line \fB124\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_SnowLambda_default\fP)"

.PP
Definition at line \fB115\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_SnowNumber\fP)"

.PP
Definition at line \fB144\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_SnowNumber_default\fP)"

.PP
Definition at line \fB135\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_VelScaleFactor_default\fP)"

.PP
Definition at line \fB154\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_VelScaleFactor_ice\fP)"

.PP
Definition at line \fB165\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBPropertyTestSuite_VelScaleFactor_snow\fP)"

.PP
Definition at line \fB176\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBThermoTestSuite_InternalEnergy\fP)"

.PP
Definition at line \fB187\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBThermoTestSuite_QSatIceRho\fP)"

.PP
Definition at line \fB240\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBThermoTestSuite_QSatRho\fP)"

.PP
Definition at line \fB230\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBThermoTestSuite_SatPresIce\fP)"

.PP
Definition at line \fB221\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBThermoTestSuite_SatPresWater\fP)"

.PP
Definition at line \fB213\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBThermoTestSuite_T_InternalEnergy\fP)"

.PP
Definition at line \fB200\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToGraupel\fP)"

.PP
Definition at line \fB260\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToGraupel_default\fP)"

.PP
Definition at line \fB250\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToRain\fP)"

.PP
Definition at line \fB281\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToRain_default\fP)"

.PP
Definition at line \fB271\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToSnow\fP)"

.PP
Definition at line \fB304\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudToSnow_default\fP)"

.PP
Definition at line \fB293\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudXIce_c\fP)"

.PP
Definition at line \fB337\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudXIce_default\fP)"

.PP
Definition at line \fB316\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_CloudXIce_i\fP)"

.PP
Definition at line \fB326\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_GraupelToRain\fP)"

.PP
Definition at line \fB359\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_GraupelToRain_default\fP)"

.PP
Definition at line \fB348\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_IceToGraupel_default\fP)"

.PP
Definition at line \fB372\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_IceToGraupel_g\fP)"

.PP
Definition at line \fB395\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_IceToGraupel_r\fP)"

.PP
Definition at line \fB383\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_IceToSnow\fP)"

.PP
Definition at line \fB417\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_IceToSnow_default\fP)"

.PP
Definition at line \fB407\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToGraupel_1\fP)"

.PP
Definition at line \fB444\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToGraupel_2\fP)"

.PP
Definition at line \fB461\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToGraupel_3\fP)"

.PP
Definition at line \fB478\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToGraupel_default\fP)"

.PP
Definition at line \fB428\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToVapor\fP)"

.PP
Definition at line \fB507\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_RainToVapor_default\fP)"

.PP
Definition at line \fB495\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_SnowToGraupel\fP)"

.PP
Definition at line \fB531\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_SnowToGraupel_default\fP)"

.PP
Definition at line \fB521\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_SnowToRain\fP)"

.PP
Definition at line \fB553\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_SnowToRain_default\fP)"

.PP
Definition at line \fB542\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXGraupel\fP)"

.PP
Definition at line \fB581\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXGraupel_default\fP)"

.PP
Definition at line \fB566\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXIce\fP)"

.PP
Definition at line \fB647\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXIce_default\fP)"

.PP
Definition at line \fB636\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXSnow\fP)"

.PP
Definition at line \fB616\fP of file \fBcommon\&.cc\fP\&.
.SS "TEST_F (\fBMuphysTest\fP, \fBTransitionTestSuite_VaporXSnow_default\fP)"

.PP
Definition at line \fB597\fP of file \fBcommon\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
