.TH "core/properties/fall_speed.hpp" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/properties/fall_speed.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./common/constants\&.hpp'\fP
.br
\fR#include '\&.\&./common/types\&.hpp'\fP
.br
\fR#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBproperty\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBtypename\fP \fBarray_t\fP > \fBTARGET\fP \fBreal_t\fP \fBproperty::fall_speed\fP (\fBreal_t\fP \fBdensity\fP, \fBarray_t\fP \fBparams\fP)"
.br
.RI "Calculates the fall speed of hydrometeors\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
