.TH "graupel_ct" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graupel_ct
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBrho_00\fP = 1\&.225"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBq1\fP = 8\&.\fBe\fP\-6"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBqmin\fP = 1\&.0e\-15"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBams\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBbms\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBv0s\fP = 25\&.0"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBv1s\fP = 0\&.5"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBm0_ice\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBci\fP = 2108\&."
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtx\fP = 3339\&.5"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtfrz_het1\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtfrz_het2\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtfrz_hom\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBlvc\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBlsc\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::ams\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    0\&.069
.fi

.PP
Definition at line \fB76\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::bms\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    2\&.0
.fi

.PP
Definition at line \fB78\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::ci = 2108\&.\fR [constexpr]\fP"

.PP
Definition at line \fB84\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::lsc\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    thermodyn::als \-
    (thermodyn::cpv \- ci) *
        thermodyn::tmelt
.fi

.PP
Definition at line \fB100\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::lvc\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    thermodyn::alv \-
    (thermodyn::cpv \- thermodyn::clw) *
        thermodyn::tmelt
.fi

.PP
Definition at line \fB96\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::m0_ice\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    1\&.0e\-12
.fi

.PP
Definition at line \fB82\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::q1 = 8\&.\fBe\fP\-6\fR [constexpr]\fP"

.PP
Definition at line \fB74\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::qmin = 1\&.0e\-15\fR [constexpr]\fP"

.PP
Definition at line \fB75\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::rho_00 = 1\&.225\fR [constexpr]\fP"

.PP
Definition at line \fB73\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::tfrz_het1\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    thermodyn::tmelt \-
    static_cast<real_t>(
        6\&.0)
.fi

.PP
Definition at line \fB86\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::tfrz_het2\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    thermodyn::tmelt \-
    static_cast<real_t>(25\&.0)
.fi

.PP
Definition at line \fB90\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::tfrz_hom\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    thermodyn::tmelt \-
    static_cast<real_t>(37\&.0)
.fi

.PP
Definition at line \fB93\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::tx = 3339\&.5\fR [constexpr]\fP"

.PP
Definition at line \fB85\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::v0s = 25\&.0\fR [constexpr]\fP"

.PP
Definition at line \fB80\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP graupel_ct::v1s = 0\&.5\fR [constexpr]\fP"

.PP
Definition at line \fB81\fP of file \fBconstants\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
