.TH "core/properties/ice_sticking.hpp" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/properties/ice_sticking.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./common/constants\&.hpp'\fP
.br
\fR#include '\&.\&./common/types\&.hpp'\fP
.br
\fR#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBproperty\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBproperty::ice_sticking\fP (\fBreal_t\fP \fBt\fP)"
.br
.RI "Calculates the sticking efficiency of ice\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBproperty::a_freez\fP = 0\&.09"
.br
.RI "scale factor for freezing depression "
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBproperty::b_max_exp\fP = 1\&.00"
.br
.RI "maximum for exponential temperature factor "
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBproperty::eff_min\fP = 0\&.075"
.br
.RI "minimum sticking efficiency "
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBproperty::eff_fac\fP"
.br
.RI "Scaling factor [1/K] for cloud ice sticking efficiency\&. "
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBproperty::tcrit\fP"
.br
.RI "Temperature at which cloud ice autoconversion starts\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
