.TH "core/properties/ice_number.hpp" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/properties/ice_number.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./common/constants\&.hpp'\fP
.br
\fR#include '\&.\&./common/types\&.hpp'\fP
.br
\fR#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBproperty\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBproperty::ice_number\fP (\fBreal_t\fP \fBt\fP, \fBreal_t\fP \fBrho\fP)"
.br
.RI "Calculates the ice crystal number concentration following the Cooper parameterization\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBproperty::a_coop\fP = 5\&.000"
.br
.RI "parameter in cooper fit "
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBproperty::b_coop\fP = 0\&.304"
.br
.RI "parameter in cooper fit "
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBproperty::nimax\fP = 250\&.\fBe\fP+3"
.br
.RI "maximal number of ice crystals "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
