.TH "idx" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
idx
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBsize_t\fP \fBnx\fP = 6"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBsize_t\fP \fBnp\fP = 4"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBsize_t\fP \fBlqr\fP = 0"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBsize_t\fP \fBlqi\fP = 1"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBsize_t\fP \fBlqs\fP = 2"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBsize_t\fP \fBlqg\fP = 3"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBsize_t\fP \fBlqc\fP = 4"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBsize_t\fP \fBlqv\fP = 5"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBsize_t\fP \fBqx_ind\fP [] = {\fBlqv\fP, \fBlqc\fP, \fBlqr\fP, \fBlqs\fP, \fBlqi\fP, \fBlqg\fP}"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBsize_t\fP \fBqp_ind\fP [] = {\fBlqr\fP, \fBlqi\fP, \fBlqs\fP, \fBlqg\fP}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBconstexpr\fP \fBsize_t\fP idx::lqc = 4\fR [constexpr]\fP"

.PP
Definition at line \fB113\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBsize_t\fP idx::lqg = 3\fR [constexpr]\fP"

.PP
Definition at line \fB112\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBsize_t\fP idx::lqi = 1\fR [constexpr]\fP"

.PP
Definition at line \fB110\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBsize_t\fP idx::lqr = 0\fR [constexpr]\fP"

.PP
Definition at line \fB109\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBsize_t\fP idx::lqs = 2\fR [constexpr]\fP"

.PP
Definition at line \fB111\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBsize_t\fP idx::lqv = 5\fR [constexpr]\fP"

.PP
Definition at line \fB114\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBsize_t\fP idx::np = 4\fR [constexpr]\fP"

.PP
Definition at line \fB108\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBsize_t\fP idx::nx = 6\fR [constexpr]\fP"

.PP
Definition at line \fB107\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBsize_t\fP idx::qp_ind[] = {\fBlqr\fP, \fBlqi\fP, \fBlqs\fP, \fBlqg\fP}\fR [constexpr]\fP"

.PP
Definition at line \fB117\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBsize_t\fP idx::qx_ind[] = {\fBlqv\fP, \fBlqc\fP, \fBlqr\fP, \fBlqs\fP, \fBlqi\fP, \fBlqg\fP}\fR [constexpr]\fP"

.PP
Definition at line \fB116\fP of file \fBconstants\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
