.TH "test/io.cc" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/io.cc
.SH SYNOPSIS
.br
.PP
\fR#include <cstdlib>\fP
.br
\fR#include <filesystem>\fP
.br
\fR#include <gtest/gtest\&.h>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <regex>\fP
.br
\fR#include <core/common/constants\&.hpp>\fP
.br
\fR#include <core/properties/thermo\&.hpp>\fP
.br
\fR#include <io/io\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdouble\fP \fBtouched_cells\fP (\fBsize_t\fP &\fBke\fP, \fBsize_t\fP &\fBivend\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBt\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBrho\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqv\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqc\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqi\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqr\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqs\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqg\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBIOTestSuite\fP, \fBCheckFile\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (\fBIOTestSuite\fP, \fBCheckFile\fP)"

.PP
Definition at line \fB47\fP of file \fBio\&.cc\fP\&.
.SS "\fBdouble\fP touched_cells (\fBsize_t\fP & ke, \fBsize_t\fP & ivend, \fBarray_1d_t\fP< \fBreal_t\fP > & t, \fBarray_1d_t\fP< \fBreal_t\fP > & rho, \fBarray_1d_t\fP< \fBreal_t\fP > & qv, \fBarray_1d_t\fP< \fBreal_t\fP > & qc, \fBarray_1d_t\fP< \fBreal_t\fP > & qi, \fBarray_1d_t\fP< \fBreal_t\fP > & qr, \fBarray_1d_t\fP< \fBreal_t\fP > & qs, \fBarray_1d_t\fP< \fBreal_t\fP > & qg)"

.PP
Definition at line \fB23\fP of file \fBio\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
