.TH "io/io.hpp" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io/io.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./core/common/types\&.hpp'\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <netcdf>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBio_muphys\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBio_muphys::NCreal_t\fP = \fBNcDouble\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBio_muphys::parse_args\fP (std::string &\fBfile\fP, \fBsize_t\fP &\fBitime\fP, \fBreal_t\fP &\fBdt\fP, \fBreal_t\fP &\fBqnc\fP, \fBint\fP \fBargc\fP, \fBchar\fP **\fBargv\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBio_muphys::input_vector\fP (\fBNcFile\fP &\fBdatafile\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBv\fP, \fBconst\fP std::string \fBinput\fP, \fBsize_t\fP &\fBncells\fP, \fBsize_t\fP &\fBnlev\fP, \fBsize_t\fP \fBitime\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBio_muphys::input_vector\fP (\fBNcFile\fP &\fBdatafile\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBv\fP, \fBconst\fP std::string \fBinput\fP, \fBsize_t\fP &\fBncells\fP, \fBsize_t\fP &\fBnlev\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBio_muphys::output_vector\fP (\fBNcFile\fP &\fBdatafile\fP, \fBarray_1d_t\fP< \fBNcDim\fP > &\fBdims\fP, \fBconst\fP std::string \fBoutput\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBv\fP, \fBsize_t\fP &\fBncells\fP, \fBsize_t\fP &\fBnlev\fP, \fBint\fP &\fBdeflate_level\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBio_muphys::output_vector\fP (\fBNcFile\fP &\fBdatafile\fP, \fBarray_1d_t\fP< \fBNcDim\fP > &\fBdims\fP, \fBconst\fP std::string \fBoutput\fP, std::map< std::string, \fBNcVarAtt\fP >, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBv\fP, \fBsize_t\fP &\fBncells\fP, \fBsize_t\fP &\fBnlev\fP, \fBint\fP &\fBdeflate_level\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBio_muphys::read_fields\fP (\fBconst\fP std::string \fBinput_file\fP, \fBsize_t\fP &\fBitime\fP, \fBsize_t\fP &\fBncells\fP, \fBsize_t\fP &\fBnlev\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBz\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBt\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &p, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBrho\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqv\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqc\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqi\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqr\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqs\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqg\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBio_muphys::write_fields\fP (\fBconst\fP \fBstring\fP \fBoutput_file\fP, \fBsize_t\fP &\fBncells\fP, \fBsize_t\fP &\fBnlev\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBt\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqv\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqc\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqi\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqr\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqs\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqg\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBio_muphys::write_fields\fP (\fBconst\fP \fBstring\fP \fBoutput_file\fP, \fBconst\fP \fBstring\fP \fBinput_file\fP, \fBsize_t\fP &\fBncells\fP, \fBsize_t\fP &\fBnlev\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBt\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqv\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqc\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqi\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqr\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqs\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBqg\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBio_muphys::log_time\fP (\fBint64_t\fP \fBvalue\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
