.TH "main.cpp" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <chrono>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include 'core/common/graupel\&.hpp'\fP
.br
\fR#include 'core/common/types\&.hpp'\fP
.br
\fR#include 'core/common/utils\&.hpp'\fP
.br
\fR#include 'io/io\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBint\fP \fBargc\fP, \fBchar\fP *\fBargv\fP[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBint\fP argc, \fBchar\fP * argv[])"

.PP
Definition at line \fB40\fP of file \fBmain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
