.TH "md__r_e_a_d_m_e" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- muphys-cpp 
.PP
 
.SH "Description"
.PP
C++ prototypes of \fRmuphys\fP project using heterogeneous libraries and C extensions\&.
.SH "Documentation"
.PP
Online documentation is generated automatically using \fRdoxygen\fP \&.
.SH "Installation"
.PP
.SS "Dependencies"
.IP "\(bu" 2
\fRNetCDF for CXX\fP
.IP "  \(bu" 4
for Levante: \fRspack load netcdf-cxx4@4\&.3\&.1\fP
.PP

.PP
.PP
Other dependency like \fRgoogletest\fP is built in-tree from github archives\&.
.SS "Available compile options"
.IP "\(bu" 2
\fIImplementation\fP - The sequential implementation is selected by default\&. The user can choose of the following options:
.IP "  \(bu" 4
MU_IMPL=seq - C++ serial implementation
.PP

.PP
.PP
\fIPrecision\fP (default is \fRdouble\fP)
.IP "\(bu" 2
MU_ENABLE_SINGLE - to switch to \fRfloat\fP
.PP
.PP
\fIUnit-test\fP - compile tests together with the main executable (default is \fRtrue\fP)
.IP "\(bu" 2
MU_ENABLE_TESTS
.PP
.SS "Compile the project (with default flags and Seq frontend)"
\fRcmake -DMU_IMPL=seq -B build -S \&.\fP
.PP
\fRcmake --build build\fP
.SH "Usage"
.PP
\fR\&./build/bin/graupel input_file\&.nc\fP
.SS "Automated tests"
.IP "\(bu" 2
Run tests manually: \fRcd build && ctest\fP
.PP
.SH "License"
.PP
muphys-cpp is available under a BSD 3-clause license\&. See \fRLICENSES/\fP for license information and \fRAUTHORS\&.TXT\fP for a list of authors\&. 
