.TH "MuphysTest" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MuphysTest \- Test fixture class for Muphys tests\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits testing::Test\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBvalidate\fP (\fBreal_t\fP \fBactual\fP, \fBreal_t\fP \fBexpected\fP)"
.br
.RI "Validates the equality of actual and expected floating-point values\&. "
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBvalidate\fP (\fBreal_t\fP \fBactual\fP, \fBreal_t\fP \fBexpected_float\fP, \fBreal_t\fP \fBexpected_double\fP)"
.br
.RI "Validates the equality of actual and expected floating-point values\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconstexpr\fP \fBreal_t\fP \fBZERO\fP = 0\&.0"
.br
.RI "A constant value representing zero\&. "
.in -1c
.SH "Detailed Description"
.PP 
Test fixture class for Muphys tests\&. 

This class provides utility functions for validating floating-point values and defines a constant value for zero\&. 
.PP
Definition at line \fB22\fP of file \fBMuphysTest\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBstatic\fP \fBvoid\fP MuphysTest::validate (\fBreal_t\fP actual, \fBreal_t\fP expected)\fR [inline]\fP, \fR [static]\fP"

.PP
Validates the equality of actual and expected floating-point values\&. This function compares the actual and expected values based on the type of \fRreal_t\fP\&.
.PP
\fBParameters\fP
.RS 4
\fIactual\fP The actual value to be compared\&. 
.br
\fIexpected\fP The expected value to compare against\&. 
.RE
.PP

.PP
Definition at line \fB33\fP of file \fBMuphysTest\&.cc\fP\&.
.SS "\fBstatic\fP \fBvoid\fP MuphysTest::validate (\fBreal_t\fP actual, \fBreal_t\fP expected_float, \fBreal_t\fP expected_double)\fR [inline]\fP, \fR [static]\fP"

.PP
Validates the equality of actual and expected floating-point values\&. This function compares the actual value with the expected values based on the type of \fRreal_t\fP\&.
.PP
\fBParameters\fP
.RS 4
\fIactual\fP The actual value to be compared\&. 
.br
\fIexpected_float\fP The expected value to compare against if \fRreal_t\fP is \fRfloat\fP\&. 
.br
\fIexpected_double\fP The expected value to compare against if \fRreal_t\fP is \fRdouble\fP\&. 
.RE
.PP

.PP
Definition at line \fB49\fP of file \fBMuphysTest\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconstexpr\fP \fBreal_t\fP MuphysTest::ZERO = 0\&.0\fR [static]\fP, \fR [constexpr]\fP"

.PP
A constant value representing zero\&. 
.PP
Definition at line \fB60\fP of file \fBMuphysTest\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
