.TH "t_qx_ptr" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_qx_ptr \- Holds pointers to data arrays and their size for various hydrometeor types\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBt_qx_ptr\fP ()"
.br
.RI "Default constructor initializes pointers to \fRnullptr\fP and size to \fR0\fP\&. "
.ti -1c
.RI "\fBt_qx_ptr\fP (\fBarray_1d_t\fP< \fBreal_t\fP > &\fBp_\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBx_\fP)"
.br
.RI "Constructor that initializes the structure with existing arrays\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBreal_t\fP * \fBp\fP"
.br
.RI "Pointer to an array holding properties of hydrometeors\&. "
.ti -1c
.RI "\fBreal_t\fP * \fBx\fP"
.br
.RI "Pointer to an array holding another set of properties, possibly related to a different aspect of the hydrometeors\&. "
.ti -1c
.RI "\fBsize_t\fP \fBsz\fP"
.br
.RI "Size of the arrays pointed to by \fRp\fP and \fRx\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Holds pointers to data arrays and their size for various hydrometeor types\&. 

This structure is designed to manage arrays related to the properties of hydrometeors, such as concentration, mass, volume, etc\&. It simplifies passing these arrays around by encapsulating the pointers to the data and the size of the arrays in a single object\&. 
.PP
Definition at line \fB45\fP of file \fBgraupel\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "t_qx_ptr::t_qx_ptr ()\fR [inline]\fP"

.PP
Default constructor initializes pointers to \fRnullptr\fP and size to \fR0\fP\&. 
.PP
Definition at line \fB53\fP of file \fBgraupel\&.cpp\fP\&.
.SS "t_qx_ptr::t_qx_ptr (\fBarray_1d_t\fP< \fBreal_t\fP > & p_, \fBarray_1d_t\fP< \fBreal_t\fP > & x_)\fR [inline]\fP"

.PP
Constructor that initializes the structure with existing arrays\&. 
.PP
\fBParameters\fP
.RS 4
\fIp_\fP Reference to an array of real numbers for the first set of properties\&. 
.br
\fIx_\fP Reference to an array of real numbers for the second set of properties\&. 
.RE
.PP

.PP
Definition at line \fB60\fP of file \fBgraupel\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBreal_t\fP* t_qx_ptr::p"

.PP
Pointer to an array holding properties of hydrometeors\&. 
.PP
Definition at line \fB46\fP of file \fBgraupel\&.cpp\fP\&.
.SS "\fBsize_t\fP t_qx_ptr::sz"

.PP
Size of the arrays pointed to by \fRp\fP and \fRx\fP\&. 
.PP
Definition at line \fB48\fP of file \fBgraupel\&.cpp\fP\&.
.SS "\fBreal_t\fP* t_qx_ptr::x"

.PP
Pointer to an array holding another set of properties, possibly related to a different aspect of the hydrometeors\&. 
.PP
Definition at line \fB47\fP of file \fBgraupel\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
