.TH "thermo" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thermo
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBinternal_energy\fP (\fBreal_t\fP \fBt\fP, \fBreal_t\fP \fBqv\fP, \fBreal_t\fP \fBqliq\fP, \fBreal_t\fP \fBqice\fP, \fBreal_t\fP \fBrho\fP, \fBreal_t\fP \fBdz\fP)"
.br
.RI "Calculates the internal energy of a system\&. "
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBT_from_internal_energy\fP (\fBreal_t\fP \fBU\fP, \fBreal_t\fP \fBqv\fP, \fBreal_t\fP \fBqliq\fP, \fBreal_t\fP \fBqice\fP, \fBreal_t\fP \fBrho\fP, \fBreal_t\fP \fBdz\fP)"
.br
.RI "Calculates the temperature from the internal energy of a system\&. "
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBspecific_humidity\fP (\fBreal_t\fP \fBpvapor\fP, \fBreal_t\fP \fBptotal\fP)"
.br
.RI "Calculates the specific humidity from vapor pressure and total pressure\&. "
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBsat_pres_water\fP (\fBreal_t\fP \fBt\fP)"
.br
.RI "Calculates the saturation pressure over water\&. "
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBsat_pres_ice\fP (\fBreal_t\fP \fBt\fP)"
.br
.RI "Calculates saturation pressure over ice\&. "
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBqsat_rho\fP (\fBreal_t\fP \fBt\fP, \fBreal_t\fP \fBrho\fP)"
.br
.RI "Calculates saturation vapor pressure (over liquid) at constant density\&. "
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBqsat_ice_rho\fP (\fBreal_t\fP \fBt\fP, \fBreal_t\fP \fBrho\fP)"
.br
.RI "Saturation vapor pressure (over ice) at constant density\&. "
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBdqsatdT_rho\fP (\fBreal_t\fP \fBqs\fP, \fBreal_t\fP \fBt\fP)"
.br
.RI "Computes the derivative d(qsat_rho)/dT\&. "
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBdqsatdT\fP (\fBreal_t\fP \fBqs\fP, \fBreal_t\fP \fBt\fP)"
.br
.RI "Computes the derivative of saturation vapor pressure (over liquid) with respect to temperature\&. "
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBdqsatdT_ice\fP (\fBreal_t\fP \fBqs\fP, \fBreal_t\fP \fBt\fP)"
.br
.RI "Computes the derivative of saturation vapor pressure (over ice) with respect to temperature\&. "
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBvaporization_energy\fP (\fBreal_t\fP \fBt\fP)"
.br
.RI "Computes internal energy of vaporization\&. "
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBsublimation_energy\fP (\fBreal_t\fP \fBt\fP)"
.br
.RI "Computes internal energy of sublimation\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBc1es\fP = 610\&.78"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBc2es\fP = \fBc1es\fP * \fBthermodyn::rd\fP / \fBthermodyn::rv\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBc3les\fP = 17\&.269"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBc3ies\fP = 21\&.875"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBc4les\fP = 35\&.86"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBc4ies\fP = 7\&.66"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBc5les\fP = \fBc3les\fP * (\fBthermodyn::tmelt\fP \- \fBc4les\fP)"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBc5ies\fP = \fBc3ies\fP * (\fBthermodyn::tmelt\fP \- \fBc4ies\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBTARGET\fP \fBreal_t\fP thermo::dqsatdT (\fBreal_t\fP qs, \fBreal_t\fP t)"

.PP
Computes the derivative of saturation vapor pressure (over liquid) with respect to temperature\&. This function computes the derivative of saturation vapor pressure over liquid water with respect to temperature, based on the saturation vapor pressure and temperature\&.
.PP
\fBParameters\fP
.RS 4
\fIqs\fP Saturation vapor pressure over liquid water (Pa)\&. 
.br
\fIt\fP Temperature (K)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The derivative of saturation vapor pressure with respect to temperature (Pa/K)\&. 
.RE
.PP

.PP
Definition at line \fB177\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBTARGET\fP \fBreal_t\fP thermo::dqsatdT_ice (\fBreal_t\fP qs, \fBreal_t\fP t)"

.PP
Computes the derivative of saturation vapor pressure (over ice) with respect to temperature\&. This function computes the derivative of saturation vapor pressure over ice with respect to temperature, based on the saturation vapor pressure and temperature\&.
.PP
\fBParameters\fP
.RS 4
\fIqs\fP Saturation vapor pressure over ice (Pa)\&. 
.br
\fIt\fP Temperature (K)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The derivative of saturation vapor pressure over ice with respect to temperature (Pa/K)\&. 
.RE
.PP

.PP
Definition at line \fB192\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBTARGET\fP \fBreal_t\fP thermo::dqsatdT_rho (\fBreal_t\fP qs, \fBreal_t\fP t)"

.PP
Computes the derivative d(qsat_rho)/dT\&. 
.PP
\fBParameters\fP
.RS 4
\fIqs\fP Saturation vapor pressure (over liquid) 
.br
\fIt\fP Temperature (kelvin) 
.RE
.PP
\fBReturns\fP
.RS 4
derivative d(qsat_rho)/dT 
.RE
.PP

.PP
Definition at line \fB162\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBTARGET\fP \fBreal_t\fP thermo::internal_energy (\fBreal_t\fP t, \fBreal_t\fP qv, \fBreal_t\fP qliq, \fBreal_t\fP qice, \fBreal_t\fP rho, \fBreal_t\fP dz)"

.PP
Calculates the internal energy of a system\&. This function calculates the internal energy of a system based on the temperature, specific mass of water vapor, liquid phases, solid phases, density, and layer thickness\&. The internal energy is computed using the moist isometric specific heat and latent heats of vaporization and sublimation\&.
.PP
\fBParameters\fP
.RS 4
\fIt\fP Temperature (K)\&. 
.br
\fIqv\fP Specific mass of water vapor (kg/kg)\&. 
.br
\fIqliq\fP Specific mass of liquid phases (kg/kg)\&. 
.br
\fIqice\fP Specific mass of solid phases (kg/kg)\&. 
.br
\fIrho\fP Density (kg/m^3)\&. 
.br
\fIdz\fP Layer thickness (m)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The internal energy of the system (J/m^2)\&. 
.RE
.PP

.PP
Definition at line \fB48\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBTARGET\fP \fBreal_t\fP thermo::qsat_ice_rho (\fBreal_t\fP t, \fBreal_t\fP rho)"

.PP
Saturation vapor pressure (over ice) at constant density\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP Temperature (kelvin) 
.br
\fIrho\fP Density 
.RE
.PP
\fBReturns\fP
.RS 4
saturation pressure 
.RE
.PP

.PP
Definition at line \fB151\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBTARGET\fP \fBreal_t\fP thermo::qsat_rho (\fBreal_t\fP t, \fBreal_t\fP rho)"

.PP
Calculates saturation vapor pressure (over liquid) at constant density\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP Temperature (kelvin) 
.br
\fIrho\fP Density 
.RE
.PP
\fBReturns\fP
.RS 4
saturation pressure 
.RE
.PP

.PP
Definition at line \fB140\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBTARGET\fP \fBreal_t\fP thermo::sat_pres_ice (\fBreal_t\fP t)"

.PP
Calculates saturation pressure over ice\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP Temperature (kelvin) 
.RE
.PP
\fBReturns\fP
.RS 4
Saturation pressure 
.RE
.PP

.PP
Definition at line \fB129\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBTARGET\fP \fBreal_t\fP thermo::sat_pres_water (\fBreal_t\fP t)"

.PP
Calculates the saturation pressure over water\&. This function calculates the saturation pressure over water based on the temperature, using an empirical formula\&.
.PP
\fBParameters\fP
.RS 4
\fIt\fP Temperature (K)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The saturation pressure over water (Pa)\&. 
.RE
.PP

.PP
Definition at line \fB119\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBTARGET\fP \fBreal_t\fP thermo::specific_humidity (\fBreal_t\fP pvapor, \fBreal_t\fP ptotal)"

.PP
Calculates the specific humidity from vapor pressure and total pressure\&. This function calculates the specific humidity based on the vapor pressure and total pressure, using the gas constants for dry air and water vapor\&.
.PP
\fBParameters\fP
.RS 4
\fIpvapor\fP Vapor pressure (Pa)\&. 
.br
\fIptotal\fP Total pressure (Pa)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The specific humidity (kg/kg)\&. 
.RE
.PP

.PP
Definition at line \fB102\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBTARGET\fP \fBreal_t\fP thermo::sublimation_energy (\fBreal_t\fP t)"

.PP
Computes internal energy of sublimation\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP Temperature (kelvin) 
.RE
.PP
\fBReturns\fP
.RS 4
Energy of sublimation 
.RE
.PP

.PP
Definition at line \fB213\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBTARGET\fP \fBreal_t\fP thermo::T_from_internal_energy (\fBreal_t\fP U, \fBreal_t\fP qv, \fBreal_t\fP qliq, \fBreal_t\fP qice, \fBreal_t\fP rho, \fBreal_t\fP dz)"

.PP
Calculates the temperature from the internal energy of a system\&. This function calculates the temperature of a system based on the internal energy, specific mass of water vapor, liquid phases, solid phases, density, and layer thickness\&. The temperature is computed by solving the internal energy equation for temperature, considering the moist isometric specific heat and latent heats of vaporization and sublimation\&.
.PP
\fBParameters\fP
.RS 4
\fIU\fP Internal energy of the system (J/m^2)\&. 
.br
\fIqv\fP Specific mass of water vapor (kg/kg)\&. 
.br
\fIqliq\fP Specific mass of liquid phases (kg/kg)\&. 
.br
\fIqice\fP Specific mass of solid phases (kg/kg)\&. 
.br
\fIrho\fP Density (kg/m^3)\&. 
.br
\fIdz\fP Layer thickness (m)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The temperature of the system (K)\&. 
.RE
.PP

.PP
Definition at line \fB77\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBTARGET\fP \fBreal_t\fP thermo::vaporization_energy (\fBreal_t\fP t)"

.PP
Computes internal energy of vaporization\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP Temperature (kelvin) 
.RE
.PP
\fBReturns\fP
.RS 4
Energy of vaporization 
.RE
.PP

.PP
Definition at line \fB203\fP of file \fBthermo\&.hpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBconstexpr\fP \fBreal_t\fP thermo::c1es = 610\&.78\fR [constexpr]\fP"

.PP
Definition at line \fB23\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermo::c2es = \fBc1es\fP * \fBthermodyn::rd\fP / \fBthermodyn::rv\fP\fR [constexpr]\fP"

.PP
Definition at line \fB24\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermo::c3ies = 21\&.875\fR [constexpr]\fP"

.PP
Definition at line \fB26\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermo::c3les = 17\&.269\fR [constexpr]\fP"

.PP
Definition at line \fB25\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermo::c4ies = 7\&.66\fR [constexpr]\fP"

.PP
Definition at line \fB28\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermo::c4les = 35\&.86\fR [constexpr]\fP"

.PP
Definition at line \fB27\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermo::c5ies = \fBc3ies\fP * (\fBthermodyn::tmelt\fP \- \fBc4ies\fP)\fR [constexpr]\fP"

.PP
Definition at line \fB30\fP of file \fBthermo\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermo::c5les = \fBc3les\fP * (\fBthermodyn::tmelt\fP \- \fBc4les\fP)\fR [constexpr]\fP"

.PP
Definition at line \fB29\fP of file \fBthermo\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
