.TH "thermodyn" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thermodyn
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBrd\fP = 287\&.04"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBcpd\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBcvd\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBcon_m\fP = 1\&.50E\-5"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBcon_h\fP = 2\&.20E\-5"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBcon0_h\fP = 2\&.40e\-2"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBeta0d\fP = 1\&.717\fBe\fP\-5"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBrv\fP = 461\&.51"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBcpv\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBcvv\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBdv0\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBrhoh2o\fP = 1000\&."
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBrhoice\fP = 916\&.7"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBcv_i\fP = 2000\&.0"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBalv\fP = 2\&.5008\fBe6\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBals\fP = 2\&.8345\fBe6\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBalf\fP = \fBals\fP \- \fBalv\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtmelt\fP = 273\&.15"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBt3\fP = 273\&.16"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBrdv\fP = \fBrd\fP / \fBrv\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBvtmpc1\fP = \fBrv\fP / \fBrd\fP \- \fBstatic_cast\fP<\fBreal_t\fP>(1\&.)"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBvtmpc2\fP = \fBcpv\fP / \fBcpd\fP \- \fBstatic_cast\fP<\fBreal_t\fP>(1\&.)"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBrcpv\fP = \fBcpd\fP / \fBcpv\fP \- \fBstatic_cast\fP<\fBreal_t\fP>(1\&.)"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBalvdcp\fP = \fBalv\fP / \fBcpd\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBalsdcp\fP = \fBals\fP / \fBcpd\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBrcpd\fP = \fBstatic_cast\fP<\fBreal_t\fP>(1\&.) / \fBcpd\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBrcvd\fP = \fBstatic_cast\fP<\fBreal_t\fP>(1\&.) / \fBcvd\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBrcpl\fP = 3\&.1733"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBclw\fP"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBcv_v\fP = (\fBrcpv\fP + \fBstatic_cast\fP<\fBreal_t\fP>(1\&.0)) * \fBcpd\fP \- \fBrv\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::alf = \fBals\fP \- \fBalv\fP\fR [constexpr]\fP"

.PP
Definition at line \fB51\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::als = 2\&.8345\fBe6\fP\fR [constexpr]\fP"

.PP
Definition at line \fB50\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::alsdcp = \fBals\fP / \fBcpd\fP\fR [constexpr]\fP"

.PP
Definition at line \fB61\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::alv = 2\&.5008\fBe6\fP\fR [constexpr]\fP"

.PP
Definition at line \fB49\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::alvdcp = \fBalv\fP / \fBcpd\fP\fR [constexpr]\fP"

.PP
Definition at line \fB60\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::clw\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
= (rcpl + static_cast<real_t>(1\&.0)) *
                       cpd
.fi

.PP
Definition at line \fB66\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::con0_h = 2\&.40e\-2\fR [constexpr]\fP"

.PP
Definition at line \fB29\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::con_h = 2\&.20E\-5\fR [constexpr]\fP"

.PP
Definition at line \fB28\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::con_m = 1\&.50E\-5\fR [constexpr]\fP"

.PP
Definition at line \fB27\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::cpd\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    1004\&.64
.fi

.PP
Definition at line \fB23\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::cpv\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    1869\&.46
.fi

.PP
Definition at line \fB35\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::cv_i = 2000\&.0\fR [constexpr]\fP"

.PP
Definition at line \fB46\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::cv_v = (\fBrcpv\fP + \fBstatic_cast\fP<\fBreal_t\fP>(1\&.0)) * \fBcpd\fP \- \fBrv\fP\fR [constexpr]\fP"

.PP
Definition at line \fB68\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::cvd\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    cpd \- rd
.fi

.PP
Definition at line \fB25\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::cvv\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    cpv \- rv
.fi

.PP
Definition at line \fB37\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::dv0\fR [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
    2\&.22e\-5
.fi

.PP
Definition at line \fB39\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::eta0d = 1\&.717\fBe\fP\-5\fR [constexpr]\fP"

.PP
Definition at line \fB30\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::rcpd = \fBstatic_cast\fP<\fBreal_t\fP>(1\&.) / \fBcpd\fP\fR [constexpr]\fP"

.PP
Definition at line \fB62\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::rcpl = 3\&.1733\fR [constexpr]\fP"

.PP
Definition at line \fB64\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::rcpv = \fBcpd\fP / \fBcpv\fP \- \fBstatic_cast\fP<\fBreal_t\fP>(1\&.)\fR [constexpr]\fP"

.PP
Definition at line \fB59\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::rcvd = \fBstatic_cast\fP<\fBreal_t\fP>(1\&.) / \fBcvd\fP\fR [constexpr]\fP"

.PP
Definition at line \fB63\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::rd = 287\&.04\fR [constexpr]\fP"

.PP
Definition at line \fB22\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::rdv = \fBrd\fP / \fBrv\fP\fR [constexpr]\fP"

.PP
Definition at line \fB56\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::rhoh2o = 1000\&.\fR [constexpr]\fP"

.PP
Definition at line \fB42\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::rhoice = 916\&.7\fR [constexpr]\fP"

.PP
Definition at line \fB44\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::rv = 461\&.51\fR [constexpr]\fP"

.PP
Definition at line \fB34\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::t3 = 273\&.16\fR [constexpr]\fP"

.PP
Definition at line \fB53\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::tmelt = 273\&.15\fR [constexpr]\fP"

.PP
Definition at line \fB52\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::vtmpc1 = \fBrv\fP / \fBrd\fP \- \fBstatic_cast\fP<\fBreal_t\fP>(1\&.)\fR [constexpr]\fP"

.PP
Definition at line \fB57\fP of file \fBconstants\&.hpp\fP\&.
.SS "\fBconstexpr\fP \fBreal_t\fP thermodyn::vtmpc2 = \fBcpv\fP / \fBcpd\fP \- \fBstatic_cast\fP<\fBreal_t\fP>(1\&.)\fR [constexpr]\fP"

.PP
Definition at line \fB58\fP of file \fBconstants\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
