.TH "utils_muphys" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils_muphys
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBcalc_dz\fP (\fBarray_1d_t\fP< \fBreal_t\fP > &\fBz\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBdz\fP, \fBsize_t\fP &\fBncells\fP, \fBsize_t\fP &\fBnlev\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP utils_muphys::calc_dz (\fBarray_1d_t\fP< \fBreal_t\fP > & z, \fBarray_1d_t\fP< \fBreal_t\fP > & dz, \fBsize_t\fP & ncells, \fBsize_t\fP & nlev)"

.PP
Definition at line \fB15\fP of file \fButils\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
