.TH "core/common/utils.hpp" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/common/utils.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'types\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButils_muphys\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fButils_muphys::calc_dz\fP (\fBarray_1d_t\fP< \fBreal_t\fP > &\fBz\fP, \fBarray_1d_t\fP< \fBreal_t\fP > &\fBdz\fP, \fBsize_t\fP &\fBncells\fP, \fBsize_t\fP &\fBnlev\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
