.TH "core/transitions/vapor_x_ice.hpp" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/transitions/vapor_x_ice.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./common/constants\&.hpp'\fP
.br
\fR#include '\&.\&./common/types\&.hpp'\fP
.br
\fR#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtransition\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBtransition::vapor_x_ice\fP (\fBreal_t\fP \fBqi\fP, \fBreal_t\fP \fBmi\fP, \fBreal_t\fP \fBeta\fP, \fBreal_t\fP \fBdvsi\fP, \fBreal_t\fP \fBdt\fP)"
.br
.RI "Calculates the rate of vapor deposition to ice\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::ami\fP = 130\&.0"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBtransition::b_exp\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
