.TH "core/properties/vel_scale_factor.hpp" 3 "Version NTU_v1.0" "ICON - Graupel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/properties/vel_scale_factor.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./common/constants\&.hpp'\fP
.br
\fR#include '\&.\&./common/types\&.hpp'\fP
.br
\fR#include 'snow_number\&.hpp'\fP
.br
\fR#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBproperty\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTARGET\fP \fBreal_t\fP \fBproperty::vel_scale_factor\fP (\fBint\fP \fBiqx\fP, \fBreal_t\fP \fBxrho\fP, \fBreal_t\fP \fBrho\fP, \fBreal_t\fP \fBt\fP, \fBreal_t\fP \fBqx\fP)"
.br
.RI "Calculates the velocity scale factor for different types of condensate\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBproperty::b_i\fP = \fBstatic_cast\fP<\fBreal_t\fP>(2\&.0) / \fBstatic_cast\fP<\fBreal_t\fP>(3\&.0)"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBreal_t\fP \fBproperty::b_s\fP = \-\fBstatic_cast\fP<\fBreal_t\fP>(1\&.0) / \fBstatic_cast\fP<\fBreal_t\fP>(6\&.0)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ICON - Graupel from the source code\&.
